### ISSUE TITLE
"No one could play my game for more than 86399999 milliseconds!" -jcreed

### ISSUE THREAD

**Issue by tom7** [jcreedcmu/wordlike#181]
I won this video game while making use of slow mode's flexible scheduling, although it did mean keeping my computer on for vacation and neglecting critical security updates for more than 10 days. When I won, it showed this:

![image](https://github.com/jcreedcmu/wordlike/assets/499244/e23b286f-3a04-459c-a0fe-6c052ef9d5ed)

Absurd! I did not complete in 16 hours 40 minutes and 23 seconds. Poppycock!
Using this loophole, a speedrunner could complete the 1000-star run with an in-game time of 0:00:00.

The culprit is of course `formatTime` [here](https://github.com/jcreedcmu/wordlike/blob/b7e2d6083dd367fa6fa7e47f1316049b5bf6a502/src/ui/render.ts#L241), which labors under the misconception that the game has ended on 1970-01-01.

**Comment by jcreedcmu** [comment]
Thank you, citizen, for this rigorous QA work.
